import { initializeApp } from "firebase/app";
const VITE_APP_FIREBASE_API_KEY = import.meta.env.VITE_APP_FIREBASE_API_KEY;
const VITE_REACT_APP_FIREBASE_AUTH_DOMAIN = import.meta.env
  .VITE_REACT_APP_FIREBASE_AUTH_DOMAIN;
const VITE_REACT_APP_FIREBASE_PROJECT_ID = import.meta.env
  .VITE_REACT_APP_FIREBASE_PROJECT_ID;
const VITE_REACT_APP_FIREBASE_STORAGE_BUCKET = import.meta.env
  .VITE_REACT_APP_FIREBASE_STORAGE_BUCKET;
const VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID = import.meta.env
  .VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID;
const VITE_REACT_APP_FIREBASE_APP_ID = import.meta.env
  .VITE_REACT_APP_FIREBASE_APP_ID;

const firebaseConfig = {
  apiKey: VITE_APP_FIREBASE_API_KEY,
  authDomain: VITE_REACT_APP_FIREBASE_AUTH_DOMAIN,
  projectId: VITE_REACT_APP_FIREBASE_PROJECT_ID,
  storageBucket: VITE_REACT_APP_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  appId: VITE_REACT_APP_FIREBASE_APP_ID,

  //   measurementId: "G-9M6442BJGD"
};

export const app = initializeApp(firebaseConfig);
